package com.solo4.core.calendar.model

data class CalendarEvent(
    val eventId: Int = 0, // should be generated by room
    val dayMillis: Long,
    val title: String,
    val description: String,
    val eventTimeMillis: Long
)