[versions]
agp = "9.2.1"
android-compileSdk = "37"
android-targetSdk = "37"
android-minSdk = "29"
androidx-activityCompose = "1.13.0"
androidx-core-ktx = "1.19.0"
androidx-room = "2.8.4"
sqlite = "2.7.0"
androidx-lifecycle = "2.11.0"
compose-compiler = "1.5.15"
compose-plugin = "1.11.1"
junit = "4.13.2"
kotlin-kotlin = "2.4.10"
kotest-runnerJunit5 = "6.2.3"
mockk = "1.14.11"
ksp = "2.3.7"
kotlin-datetime = "0.8.0"
serialization = "1.11.0"
kotlin-coroutines = "1.11.0"
decompose = "3.5.0"
koin = "4.2.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-room-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-roomTesting = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-room-roomPaging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-lifecycle-lifecycleRuntimeKtx = { module="androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotest-runnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest-runnerJunit5" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

decompose-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensionsCompose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin-coroutines" }

serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-kotlin" }
kotlin-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-kotlin" }
room = { id = "androidx.room", version.ref = "androidx-room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-kotlin" }