package com.solo4.calendarreminder.data.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class CalendarEvent(
    val eventId: Int = 0, // should be generated by room
    val dayMillis: Long,
    val title: String,
    val description: String,
    val eventTimeMillis: Long
) : Parcelable