package com.solo4.calendarreminder.data.model

data class CalendarEvent(
    val eventId: Int = -1, // should be generated by room
    val dayMillis: Long,
    val title: String,
    val description: String,
    val eventTimeMillis: Long
)